language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-julietweb' ]; then cd .. && eval "mv $currentfolder generator-julietweb" && cd generator-julietweb; fi

